export const SET_SINGER = 'SET_SINGER'

export const SET_PLAYING_STATE = 'SET_PLAYING_STATE'

export const SET_FULL_SCREEN = 'SET_FULL_SCREEN'

export const SET_PLAYLIST = 'SET_PLAYLIST'

export const SET_SEQUENCE_LIST = 'SET_SEQUENCE_LIST'

export const SET_PLAY_MODE = 'SET_PLAY_MODE'

export const SET_CURRENT_INDEX = 'SET_CURRENT_INDEX'

export const SET_DISC = 'SET_DISC'

export const SET_SINGERID = 'SET_SINGERID'

export const SET_TOPLIST = 'SET_TOPLIST'

export const SET_SEARCHHISTORY = 'SET_SEARCHHISTORY'

export const SET_PLAYHISTORY = 'SET_PLAYHISTORY'

export const SET_SHOUCANGLIST = 'SET_SHOUCANGLIST'
